field: 99307c2f-aef4-47e5-b0d6-8e2fd644d90c
fieldLayouts:
  262d2c37-07b0-4025-855a-09e9f44407ce:
    tabs:
      -
        elements:
          -
            fieldUid: 1e0bfac4-e5ab-48f2-ab48-6672d5b961b8
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 03ec6cbd-a743-4f18-bf4b-e2808252a3d8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 008cbb5e-18d4-4557-bd22-7a1ba169f75d
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5cbb6ae2-83e9-48cc-8ee7-3468c307ce4e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            fieldUid: ddafc581-7c57-40f2-8604-dfc7ecbc31e9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  008cbb5e-18d4-4557-bd22-7a1ba169f75d:
    contentColumnType: text
    fieldGroup: null
    handle: richText
    instructions: ''
    name: 'Rich Text'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  03ec6cbd-a743-4f18-bf4b-e2808252a3d8:
    contentColumnType: text
    fieldGroup: null
    handle: subheadline
    instructions: ''
    name: Subheadline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  1e0bfac4-e5ab-48f2-ab48-6672d5b961b8:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5cbb6ae2-83e9-48cc-8ee7-3468c307ce4e:
    contentColumnType: text
    fieldGroup: null
    handle: ctaButton
    instructions: ''
    name: 'CTA Button'
    searchable: false
    settings:
      selectionLabel: ' -- Select link type --'
      types:
        __assoc__:
          -
            - vadfbogy
            -
              __assoc__:
                -
                  - class
                  - flipbox\craft\link\types\Entry
                -
                  - label
                  - Entry
                -
                  - showTarget
                  - ''
                -
                  - allowText
                  - '1'
                -
                  - requireText
                  - '1'
                -
                  - sources
                  -
                    - singles
                    - 'section:4806c5ad-88d9-43d3-abea-d6a110289b8e'
                    - 'section:f960fa3a-d667-4070-80be-57b945d9d897'
                -
                  - targetSiteId
                  - null
                -
                  - viewMode
                  - null
                -
                  - selectionLabel
                  - ''
                -
                  - localizeRelations
                  - false
          -
            - aroszfyc
            -
              __assoc__:
                -
                  - class
                  - flipbox\craft\link\types\Url
                -
                  - label
                  - Url
                -
                  - showTarget
                  - '1'
                -
                  - allowText
                  - '1'
                -
                  - requireText
                  - '1'
                -
                  - placeholder
                  - ''
                -
                  - useUrlAsDefaultText
                  - '1'
                -
                  - allowRelativeUrl
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: flipbox\craft\link\fields\Link
  ddafc581-7c57-40f2-8604-dfc7ecbc31e9:
    contentColumnType: string
    fieldGroup: null
    handle: ctaStyle
    instructions: ''
    name: 'CTA Style'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Button
            -
              - value
              - button
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Link
            -
              - value
              - link
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: headlinesAndText
name: 'Headlines and Text'
sortOrder: 2
