field: 99307c2f-aef4-47e5-b0d6-8e2fd644d90c
fieldLayouts:
  4cb059ac-6553-4447-9bd7-dc498771c485:
    tabs:
      -
        elements:
          -
            fieldUid: b321decb-7590-468e-b55e-2b68b58592e0
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b321decb-7590-468e-b55e-2b68b58592e0:
    contentColumnType: string
    fieldGroup: null
    handle: row
    instructions: ''
    name: Row
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 252a44ac-cb55-43ff-bc38-f746695d61e6
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - ddd20578-d9c8-4696-af19-09b633279d5a
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - b1e70e12-346a-4ca8-a95a-e2b4fbe2d855
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - af2190ee-d330-48e0-8d54-611be5256a2f
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_10_row}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: imageBlocks
name: 'Image Blocks'
sortOrder: 4
