field: 99307c2f-aef4-47e5-b0d6-8e2fd644d90c
fieldLayouts:
  88cae4a2-feb5-4c56-aa7d-bb108e6d01b0:
    tabs:
      -
        fields:
          9fe52807-0518-4dca-a594-e567cf24290f:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  9fe52807-0518-4dca-a594-e567cf24290f:
    contentColumnType: string
    fieldGroup: null
    handle: row
    instructions: ''
    name: Row
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - b1792bf0-1ecc-4400-bef4-3d1d091c5f15
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 76db206c-3545-4df5-894f-5adaf51add96
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 6b49af58-446f-4157-ae36-eafbcd9ca3ec
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - a94448e0-6439-47a7-96e6-c0cd02006d7f
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - f2929e86-c399-445c-9713-10c5e1d5af1a
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - bd7350de-8556-4f6f-8d0a-c89297e0956b
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_2_row}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: zPattern
name: 'Z Pattern'
sortOrder: 2
