fieldLayouts:
  8e3f86e2-3b62-413b-a75c-1daae77f0428:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: e3332c98-28a1-4961-a6a6-bfd47b8c7eba
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eae3cf77-624e-42b3-8b96-14a0dafc2da6
            instructions: 'Display to the left of contact form.'
            label: 'Contact Message'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 66f839dc-4b95-4019-92ab-c7925af409d4
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4ecf8285-3013-4e30-8e13-f2ccdfdf1f22
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Overview
        sortOrder: 1
      -
        elements:
          -
            fieldUid: d45f6178-2985-48cc-8c2c-bc5fa4f42307
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ec369219-48be-4613-a41d-4cdcd5a68df0
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page Header'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 99307c2f-aef4-47e5-b0d6-8e2fd644d90c
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page Sections'
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 6ff83daa-c3e8-40cf-ae52-ada18d7d91b3
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 38ddc493-2d39-48bc-a7d9-4112d20badd2
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9c0220b0-176d-4fe7-9500-dc1401aab110
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d922a4c3-0bdc-4495-93a8-f132f998c27f
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fb3fab94-bbeb-4eb9-bbcc-b47c8a8e68ad
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ae4c86d7-36b3-4565-86f0-9884f587ef0c
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 48d27cfc-9d6c-4cbe-b05a-b5770d3231da
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b68881a1-d09d-48d0-a619-d4e62fabec61
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 4
handle: contactPage
hasTitleField: true
name: 'Contact Page'
section: f960fa3a-d667-4070-80be-57b945d9d897
sortOrder: 6
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
