fieldLayouts:
  3f8e8f2e-a4be-47e0-ae40-bcae5b548360:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: d45f6178-2985-48cc-8c2c-bc5fa4f42307
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 7f8134ae-d0f0-4cd5-9118-9468b5359a15
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 5d5cc0a2-d171-4dea-b883-9fdb8e5eaec6
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f8dcdd3c-40cc-4fba-8903-081e55374e45
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f6f570c2-2ab3-4658-977e-dce645c3f39e
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: eae3cf77-624e-42b3-8b96-14a0dafc2da6
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Overview
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 6ff83daa-c3e8-40cf-ae52-ada18d7d91b3
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 38ddc493-2d39-48bc-a7d9-4112d20badd2
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 9c0220b0-176d-4fe7-9500-dc1401aab110
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d922a4c3-0bdc-4495-93a8-f132f998c27f
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: fb3fab94-bbeb-4eb9-bbcc-b47c8a8e68ad
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ae4c86d7-36b3-4565-86f0-9884f587ef0c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 48d27cfc-9d6c-4cbe-b05a-b5770d3231da
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b68881a1-d09d-48d0-a619-d4e62fabec61
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: products
hasTitleField: true
name: Products
section: 4806c5ad-88d9-43d3-abea-d6a110289b8e
sortOrder: 1
titleFormat: ''
