contentColumnType: text
fieldGroup: fac5537d-5369-4ff9-89a9-d5e9afd69e6d
handle: notificationEmail
instructions: 'The email address to send notifications to. Separate by commas to add more than one.'
name: 'Notification Email'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
