contentColumnType: string(255)
fieldGroup: fac5537d-5369-4ff9-89a9-d5e9afd69e6d
handle: pinterestLink
instructions: ''
name: 'Pinterest Link'
searchable: true
settings:
  maxLength: '255'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
