contentColumnType: string
fieldGroup: ac373799-0c0c-4016-b709-6b3ea4d28372
handle: productImages
instructions: 'The first image will be displayed in product lists. Always use large detailed images, to leverage the image zoom feature on product detail pages.'
name: 'Product Images'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:7e69bf30-61ad-4925-bef9-3cbaab1b1803'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:7e69bf30-61ad-4925-bef9-3cbaab1b1803'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: ''
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
