contentColumnType: text
fieldGroup: 53d1a5ed-a407-46f6-b9e2-ee7bac6c8932
handle: richText
instructions: ''
name: 'Rich Text'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: true
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
