field: b321decb-7590-468e-b55e-2b68b58592e0
fieldLayouts:
  6e37d0ae-bdb0-49e8-93a5-9bac5e350560:
    tabs:
      -
        elements:
          -
            fieldUid: 252a44ac-cb55-43ff-bc38-f746695d61e6
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ddd20578-d9c8-4696-af19-09b633279d5a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b1e70e12-346a-4ca8-a95a-e2b4fbe2d855
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: af2190ee-d330-48e0-8d54-611be5256a2f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  252a44ac-cb55-43ff-bc38-f746695d61e6:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:7e69bf30-61ad-4925-bef9-3cbaab1b1803'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:7e69bf30-61ad-4925-bef9-3cbaab1b1803'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:7e69bf30-61ad-4925-bef9-3cbaab1b1803'
        - 'volume:d4918dc3-2cc2-4b07-ba1b-6c9dde83c8ae'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  af2190ee-d330-48e0-8d54-611be5256a2f:
    contentColumnType: string
    fieldGroup: null
    handle: entry
    instructions: 'An entry you''d like this block to link to.'
    name: Entry
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources:
        - singles
        - 'section:4806c5ad-88d9-43d3-abea-d6a110289b8e'
        - 'section:f960fa3a-d667-4070-80be-57b945d9d897'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  b1e70e12-346a-4ca8-a95a-e2b4fbe2d855:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'This text only shows on hover'
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '3'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ddd20578-d9c8-4696-af19-09b633279d5a:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
