enableVersioning: true
handle: locations
name: Locations
propagationMethod: all
siteSettings:
  696b3395-9e92-4b02-9ba9-94c066f4348c:
    enabledByDefault: true
    hasUrls: true
    template: locations/_entry
    uriFormat: 'locations/{slug}'
type: channel
