enableVersioning: true
handle: productPortfolio
name: 'Product Portfolio'
propagationMethod: all
siteSettings:
  696b3395-9e92-4b02-9ba9-94c066f4348c:
    enabledByDefault: true
    hasUrls: true
    template: portfolio/_index
    uriFormat: portfolio
type: single
