enableVersioning: true
handle: regions
name: Regions
propagationMethod: all
siteSettings:
  696b3395-9e92-4b02-9ba9-94c066f4348c:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: ''
structure:
  maxLevels: 1
  uid: 3b169b89-a2c5-4545-9829-c16e1087dc0d
type: structure
