enableVersioning: true
handle: topNav
name: 'Main Menu'
propagationMethod: all
siteSettings:
  696b3395-9e92-4b02-9ba9-94c066f4348c:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: ''
structure:
  maxLevels: null
  uid: 25a7e425-f1ca-4a04-b81f-85d74b4edc3b
type: structure
